config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :users, only:[:show, :edit, :update, :index]
  resources :books, only:[:show, :edit, :update, :index, :create, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  # いいね機能
  has_many :favorites, dependent: :destroy
  # コメント機能
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
	end

	def after_sign_out_path_for(resource)
	  root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :ensure_comment_user, only: :destroy

  def create
    book = Book.find(params[:book_id])
    book_comment = BookComment.new(book_comment_params)
    book_comment.user_id = current_user.id
    book_comment.book_id = book.id
    book_comment.save!
    redirect_to book_path(book)
  end

  def destroy
    book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    book_comment.destroy
    redirect_to book_path(book_comment.book_id)
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

  def ensure_comment_user
    book_comment = BookComment.find_by(id: params[:id], book_id: params[:book_id])
    if book_comment.user_id != current_user.id
      redirect_to book_path(book_comment.book_id)
    end
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit,:update,:destroy]}

  def show
    @user = current_user
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end

	def create
    @user = current_user
		@book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have creatad book successfully."
		  redirect_to  book_path(@book.id)
    else
      @books = Book.all
      flash[:notice]= "errors prohibited this obj from being saved:"
      render "index"
    end
	end

  def index
    @user = current_user
    @books = Book.all
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to  book_path(@book.id)

    else
      @books = Book.all
      flash[:notice]= "errors prohibited this obj from being saved:"
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/books"
  end



	private

    def book_params
      params.require(:book).permit(:title, :body)
    end

    def user_params
      params.require(:user).permit(:name,:profile_image,:introduction)
    end

    def ensure_current_user
      @book = Book.find(params[:id])
      if @book.user_id != current_user.id
        redirect_to books_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back fallback_location: root_path
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back fallback_location: root_path
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_current_user, {only: [:edit,:update,:destroy]}


  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      flash[:notice] = "errors prohibited this obj from being saved:"
      render :edit
    end
  end


  private

    def book_params
      params.require(:book).permit(:title, :body)
    end

    def user_params
      params.require(:user).permit(:name,:profile_image,:introduction)
    end

    def ensure_current_user
      @user = User.find(params[:id])
      if @user.id != current_user.id
        redirect_to user_path(current_user.id)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_favorite.html.erb
<td>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book.id), class: "fas fa-heart", method: :delete do %>
      <%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book.id), class: "fas fa-heart", method: :post do %>
      <%= book.favorites.count %>
    <% end %>
  <% end %>
</td>

app/views/books/_newbook.html.erb
<%= form_with model: book, url: books_path, local: true do |f| %>

  <% if book.errors.any? %>
  	<div class="alert">
    	<h4>error!</h4>
    	<ul>
      	<% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    	</ul>
  	</div>
  <% end %>

    <div class="form-group">
      <label for="inputTitle">Title</label>
      <%= f.text_field :title,class: "form-control book_title" %>
    </div>

    <div class="form-group">
    <label for="inputOpinion">Opinion</label>
      <%= f.text_area :body,class: "form-control book_body" %>
    </div>

    <div class="form-group">
      <%= f.submit 'Create Book',class: "btn btn-sm btn-success" %>
    </div>
  <% end %>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <label for="bookTitle">Title</label>
          <%= f.text_field :title, autofocus: true, id:"bookTitle", class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="bookOpinion">Opinion</label>
          <%= f.text_area :body, autofocus: true, id:"bookOpinion", class: "form-control book_opinion" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
        <p>
	      <span class="show">
		    <%= link_to "Show", book_path(@book.id) %>
	      </span>
      	<span>|</span>
	      <span class="back">
	    	<%= link_to "Back", books_path %>
	      </span>
	      </p>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/profile', user: current_user %>

        <h2>New book</h2>
        <%= render 'books/newbook', book: @book %>

      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>

          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
              <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size:'40x40',format: 'no_image.jpg' %>
              </td>
              <% end %>

              <td><%= link_to book.title, book_path(book.id)%></td>
              <td><%= book.body %></td>
              <!--いいねボタン-->
              <%= render "books/favorite", book: book %>

              <!--コメント数-->
              <td><%= "コメント数: #{book.book_comments.count}" %></td>
            </tr>
            <% end %>
          </tbody>

        </table>

      </div>

    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @book.user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @book.user.introduction %></th>
            </tr>
          </tbody>
        </table>

        <div class="row">
          <%= link_to"", edit_user_path(@book.user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog"%>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book_new, url: books_path, local: true do |f| %>

        <% if @book_new.errors.any? %>
  		    <div class="alert">
    		    <h4>error!</h4>
    		    <ul>
      		    <% @book_new.errors.full_messages.each do |message| %>
        		  <li><%= message %></li>
      		    <% end %>
    		    </ul>
  		    </div>
  	    <% end %>

        <div class="form-group">
          <label for="inputTitle">Title</label>
          <%= f.text_field :title,class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="inputOpinion">Opinion</label>
          <%= f.text_area :body,class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book',class: "btn btn-sm btn-success" %>
        </div>
        <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class='table'>

          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user_id) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg",size:'40x40',format: 'no_image.jpg' %>
                <br>
                <%= @book.user.name %>
                <% end %>
              </td>


              <td><%= link_to @book.title, book_path(@book.id)%></td>
              <td><%= @book.body %></td>

              <!--Edit Destroyボタン-->
              <% if @book.user_id == current_user.id %>
              <td><%= link_to"Edit", edit_book_path(@book.id),class:"btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), class:"btn-sm btn-danger", method: :delete, data: {confirm: "本当に消しますか？"} %></td>
              <% end %>

              <!--いいねボタン-->
              <%= render "books/favorite", book: @book %>

              <!--コメント数-->
              <td><%= "コメント数: #{@book.book_comments.count}" %></td>

            </tr>
          </tbody>
        </table>

        <% @book_comments.each do |book_comment| %>
          <% if @book.id == book_comment.book_id %>
            <div>
              <%= attachment_image_tag book_comment.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size:'40x40', format: 'no_image.jpg' %>
              <%= book_comment.comment %>
              <% if book_comment.user_id == current_user.id %>
                <%= link_to "Destroy", book_book_comment_path(@book.id, book_comment.id), class:"btn-sm btn-danger", method: :delete %></td>
              <% end %>
              <br>
              <%= link_to book_comment.user.name, user_path(book_comment.user_id) %>
            </div>

          <% end %>
        <% end %>

        <!--新規コメント-->
        <div class="new-comment">
          <%= form_with(model: [@book, @book_comment], local: true) do |f| %>
          <div class="form-group">
            <%= f.text_area :comment, rows:'5', class: "form-control book_comment" %>
          </div>
          <div class="form-group">
            <%= f.submit '送信' %>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions, inpressions, and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <nav>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li><%= link_to " Home", user_path(current_user.id),class:"fas fa-home nav-link text-light" %></li>
                <li><%= link_to " Users", "/users",class:"fas fa-users nav-link text-light" %></li>
                <li><%= link_to " Books", "/books",class:"fas fa-book-open nav-link text-light" %></li>
                <li><%= link_to " logout", destroy_user_session_path,class:"fas fa-sign-out-alt nav-link text-light",method: :delete %></li>

              <% else %>
                <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
                <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
                <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
                <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
              <% end %>
            </<ul>
          </nav>
        </div>
      </nav>
    </header>

    <div class="notice">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
    </div>

    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_profile.html.erb
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" ,format: 'no_image.jpg' %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>

      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to"",edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog"%>
  </div>

app/views/users/edit.html.erb
<main>
  <div class="container">

    <% if @user.errors %>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
        </ul>
    <% end %>

    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model:@user, local:true do |f| %>

        <% if @user.errors.any? %>
  		    <div class="alert">
    		    <h4>error!</h4>
    		    <ul>
      		    <% @user.errors.full_messages.each do |message| %>
        		  <li><%= message %></li>
      		    <% end %>
    		    </ul>
  		    </div>
  	    <% end %>

        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class: "form-control name" %>
        </div>
        <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>
        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/profile', user: current_user %>

        <h2>New book</h2>
        <%= render 'books/newbook', book: @book %>

      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class='table table-hover table-inverse'>

          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg",size:'30x30',format: 'no_image.jpg' %></td>
              <td><%= user.name %></td>
              <td><%= link_to"Show",user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>

        </table>

      </div>

    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/profile', user: @user %>

        <h2>New book</h2>
        <%= render 'books/newbook', book: @book %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>

          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg",size:'40x40',format: 'no_image.jpg' %>
                <% end %>
              </td>


              <td><%= link_to book.title, book_path(book.id)%></td>
              <td><%= book.body %></td>
              <%= render "books/favorite", book: book %>

              <!--コメント数-->
              <td><%= "コメント数: #{book.book_comments.count}" %></td>
            </tr>
            <% end %>
          </tbody>

        </table>

      </div>

    </div>
  </div>
</main>